language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
services:
  - mongodb
matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      env: PUBLISH_DOCS=1
    - python: nightly
  allow_failures:
    - python: nightly


install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .[complete]
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt
  - pip install sphinxcontrib-openapi

env:
  global:
    # Doctr deploy key for ke-zhang-rd/amostra
    - secure: "HEU6oJGxVlDUDmEJlhSRXgS93lPug3FhuAyb5uRwz4GM3hwx1IJNqNxRVYG7Uxi1cIyQu4rQJueSAJXSBZDpkQ9Hrs5dW2nz7v0AkZRxnNE/bamOA+HJZY0hsPpV/Gwl7FcSUD6TVjkK2U9lR3r24oO7BGBR6PgMtpF3Oqz7Q9JnEOqCa0Em7k7ozlKjBdOfITT5g2MSDF+tPy1+7o03OA4c8z4nm22tPPDQlqpvUZDTZ9gR0GxMnriZlGYWQTMULijTBcXGCCGDme+53UoKYgOj6GREN7jmZfhQulnwL3toYMzl3OUKJIlk6SMtabSTxZJSo/R604Gdo2Sj4H5EP+Eq5DwK7T01Rwjt4IJ7pg1T49mRUXcWCwCo+CG/QF7R1KLDlPQdpczZ4N8SSMRjlOaJq5d5uLUjXmxe79Wcg3joeWl62aDeUs94nvEQ+1CUatpds2AE+/6NOu3CI1nNch6yy7LDOvgl30KjjX2vHT8WXkWHmlK0OW9hBEcOj/7T+ys6e1g8YUqNyJqR5g46pS7hqGcXSUvueQ9bMdbFw6VZGDY/gjA4py5k1853Kl45cW/CfS3xOvzb/wOVArEfU+uFbFWbpi5kJvMhYGnONDbar+jWdpXNxke7LTOobd2xVJlZBHfLeLRIaIYRCN+IdF5hB/6X+BnPfWjyLxA/Z4I="


script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - isort  --check-only  # Verify sorted imports.
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - set -e  # If any of the following steps fail, just stop at that point.
  - pip install sphinxcontrib-openapi
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --deploy-repo ke-zhang-rd/ke-zhang-rd.github.io --deploy-branch-name master amostra;

