language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
services:
  - mongodb
matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      env: PUBLISH_DOCS=1
    - python: nightly
  allow_failures:
    - python: nightly


install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .[complete]
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt
  - pip install sphinxcontrib-openapi

env:
  global:
    # Doctr deploy key for ke-zhang-rd/amostra
    - secure: "Mp0wlEid2zUyQQ5tERpzBb8+yI5OJHgV8TNSwYK4hfTcfM84mVgp4GRscPaT5f+YppKtW4+JTddEb5IXnlNjKvs8GWA5Pl6sFzfGR8VQUSXsGXCzb5Ux2214ZfFjm4TWmrz3q4dBbV2MXm0qtxqbKnxP4TlhADo3U5hG0nGWWtya0WHkWgDlsJqcSeFvtdcO+o5pO5sPrGuvuJUA75fVO4nHHW2IIKZQoVLswgcla/a15/1XO2YwZxfvKM2R9kOGOiGmY7h632K6X3HdWIbfOtp6V8fHjmyb2S8A77L9tVqfGmuA2iBuNs7ikHMQYRIOFlOb8bimjkUYv1GFi7KkU4LpuCJ1t3NTGuntzxrf7KsErqOBepRA8JZQfhTo3SthDZ7OoQTE+DdXvXY22T0Udlbu3PwutIGuz15IWfyMbTqDMIrk81dSV68BVjHo4zOiIxLdzGVsmvNaxtM316/a1A4I2zxm2iVK3C+G/pTPW0ioQVDAsaXrkJ8FpWv2uskmma9lelem+PnDrbx6p0xDM72KLYOp0Yzx1p8QrFyKt8T2nk98ZTohpVcPmIqB48rxej0L0RC/ecviLkIi950q9sXTS7pRKNusCmDd2vgQmhes0ABx86HMvZt/6WV/Ijc36wWgT2ulBV/UYAjqI2NJ7rQPbzeE+wB2JYDd0mXwVx0="

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - isort  --check-only  # Verify sorted imports.
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - set -e  # If any of the following steps fail, just stop at that point.
  - pip install sphinxcontrib-openapi
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --deploy-repo ke-zhang-rd/ke-zhang-rd.github.io --deploy-branch-name master amostra;

