language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
services:
  - mongodb
matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      env: PUBLISH_DOCS=1
    - python: nightly
  allow_failures:
    - python: nightly


install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .[complete]
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt


env:
  global:
    # Doctr deploy key for NSLS-II/NSLS-II.github.io
    - secure: "ZA6Dukalzbg2RfUjbfekeueIKm78/eFH7I0KrofVhcQiqY3l2xVmv2bQzZzqRwglES1Oi1yNQuWGiv2XYOg/Wnr89vLp6d2NpxoE7Gu+qGW9pfJnn2ekhUIM5w9RumY2BTUs5IhVtl/oVTtmVwvFNxpnScgwOXTAoaLAEtBNJxCSLFl27piZubVmz7VgGx5tEsF27RGxVrpUljmJbPIIs9XPMFj2dekanDkNeMog5Wj3OyFCE33vY7Mo1rRALm4oGq03BpQvidhNb5wJtQfc3JmArvkWXIdYB+YIWca/YL+9fzehp+fYWtYLQ1/Zbbj+1bVGRrKzpr4B1EqhVtL5DCbbJ5ltMVKNOUFed/P2b2C3nUD2S1zf5j8cUBEefsUzhYiIFRrJBBeT8Xz0q6Gds4/YtzysPzEC6KwDbAReA8JJCqFcbcoeOoS5J+bdOuZf4ci+Oxrog7Gg3Ea4t/geU+7L8VyNdWZtOw6Zw80GyNIZ1D9Z+uOuF00gan0O1XzeUCOWm//32uuDXB3dHHDMLjKxvp4FRmt5s7R1oNonQ8tDXYam4yfqozTmgXKsOZ+g67sbLOb9MltOhRJziTAgR1Te0/WEekIh7UZcMekwGbEmzYMH8CRE1NCakoESITTtqDrVtyGjHsbE4KFS6NTgQRMwmStx3k8BV2BrKysFMao="


script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - isort  --check-only  # Verify sorted imports.
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - make -C docs html  # Build the documentation.
  - |
    if [ $PUBLISH_DOCS ]; then
      # Publish docs.
      pip install doctr 
      doctr deploy --deploy-repo ke-zhang-rd/ke-zhang-rd.github.io --deploy-branch-name master amostra;
    fi
